// src/app/layout.tsx

import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar'; // Importa el componente Navbar

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'EWO Pagina Web',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar /> {/* Renderiza el Navbar */}
        {children}
      </body>
    </html>
  );
}